Repository AY2324S1-CS2103T-T13-3/tp, pull requests merged in 2023-11, with the labels that each got.

#231 Delivery edit feature
  docs/DeveloperGuide.md
  src/main/java/seedu/address/Main.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/customer/CustomerAddCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerDeleteCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerEditCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerFindCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerViewCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryAddCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryDeleteCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryEditCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/delivery/DeliveryEditCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/delivery/Delivery.java
  src/test/data/Authentication/authentication.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeliveryAddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeliveryEditDescriptorTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerAddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerAddCommandTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerEditCommandTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerEditDescriptorTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerFindCommandTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerViewCommandTest.java
  src/test/java/seedu/address/logic/commands/delivery/DeliveryEditCommandTest.java
  src/test/java/seedu/address/logic/commands/user/UserUpdateCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CustomerEditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/customer/CustomerAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/delivery/DeliveryAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/delivery/DeliveryEditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/delivery/DeliveryStatusCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/CustomerTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/UniqueCustomerListTest.java
  src/test/java/seedu/address/testutil/CustomerBuilder.java
  src/test/java/seedu/address/testutil/CustomerEditDescriptorBuilder.java
  src/test/java/seedu/address/testutil/CustomerUtil.java
  src/test/java/seedu/address/testutil/DeliveryAddDescriptorBuilder.java
  src/test/java/seedu/address/testutil/DeliveryBuilder.java
  src/test/java/seedu/address/testutil/DeliveryEditDescriptorBuilder.java
  src/test/java/seedu/address/testutil/DeliveryUtil.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#278 Increase Code Quality of data folder creation
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/storage/BookStorage.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonDeliveryBookStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonDeliveryBookStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: type.Bug, severity.Low

#267 Delivery List - Wrong Error Format
  src/main/java/seedu/address/logic/parser/DeliveryListParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/delivery/DeliveryListParserTest.java
Labels: priority.High

#270 Check for customerId and Phone to determine same Customer
  src/main/java/seedu/address/logic/commands/customer/CustomerEditCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Customer.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/DeliveryAddCommandTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerAddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerAddCommandTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerEditCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/CustomerTest.java
  src/test/java/seedu/address/model/person/UniqueCustomerListTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug, severity.High

#321 Fix deliveryid bug
  src/main/java/seedu/address/model/ModelManager.java
Labels: priority.High

#294 Edit display after customer delete
  src/main/java/seedu/address/logic/commands/customer/CustomerDeleteCommand.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.Bug, priority.Medium

#317 Fix bugs related to user
  src/main/java/seedu/address/logic/commands/user/UserRecoverAccountCommand.java
  src/main/java/seedu/address/logic/commands/user/UserUpdateCommand.java
  src/main/java/seedu/address/logic/parser/user/UserUpdateCommandParser.java
  src/test/java/seedu/address/logic/parser/user/UserUpdateCommandParserTest.java
Labels: type.Bug, priority.Medium

#291 Update UI UML diagram
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
Labels: type.Docs

#325 323 bug delivery list date
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/delivery/Date.java
  src/main/java/seedu/address/model/delivery/DeliveryDate.java
  src/main/java/seedu/address/model/delivery/OrderDate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/delivery/DeliveryListCommandTest.java
  src/test/java/seedu/address/logic/parser/delivery/DeliveryListParserTest.java
Labels: priority.High

#327 Update Note to not allow non-alphanumeric strings
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/delivery/Note.java
  src/main/java/seedu/address/storage/JsonAdaptedDelivery.java
  src/test/java/seedu/address/model/delivery/DeliveryTest.java
  src/test/java/seedu/address/model/delivery/NoteTest.java
Labels: type.Bug, priority.Medium

#330 Remove Sample Data Auto Generation
  src/main/java/seedu/address/MainApp.java
Labels: priority.High, type.Task

#328 CReplace index with ID
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/customer/CustomerEditCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryCreateNoteCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryEditCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/customer/CustomerEditCommandTest.java
  src/test/java/seedu/address/logic/commands/delivery/DeliveryEditCommandTest.java
Labels: type.Bug, priority.High

#322 Update UG for DeliveryFindCommand
  docs/UserGuide.md
  docs/images/delivery/delivery_find.png
  docs/images/delivery/delivery_find_before.png
Labels: priority.Medium, type.Task, type.Docs

#289 Add FAQ
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Docs

#302 Update UG features and format
  docs/UserGuide.md
  docs/stylesheets/main.css
Labels: type.Bug, priority.High, type.Docs

#288 Add Command Summary
  docs/UserGuide.md
Labels: severity.High, type.Docs

#313 Update Ui.png with current Application UI
  docs/images/Ui.png
Labels: priority.Low, type.Task, type.Docs

#303 Add Getting Started Guide to UG
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  docs/images/getting-started/CommandBox.png
  docs/images/getting-started/CommandResultFeedback.png
  docs/images/getting-started/CustomerAdded.png
  docs/images/getting-started/CustomerList.png
  docs/images/getting-started/DeliveryAdded.png
  docs/images/getting-started/DeliveryID.png
  docs/images/getting-started/DeliveryList.png
  docs/images/getting-started/HomePage.png
  docs/images/getting-started/StartPage.png
  docs/stylesheets/main.css
Labels: priority.High, type.Task, type.Docs

#310 304 ug delivery list delivery view
  docs/UserGuide.md
  docs/images/delivery/DeliveryListSuccess.png
  docs/images/delivery/DeliveryViewSuccess.png
  docs/images/delivery/delivery_list.png
  docs/images/delivery/delivery_view.png
Labels: priority.High, type.Docs

#334 333 bug delivery list message
  src/main/java/seedu/address/logic/commands/delivery/DeliveryListCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryViewCommand.java
Labels: priority.High, severity.High

#315 Update UG formatting
  docs/UserGuide.md
  docs/images/customer/customerAdd_after.png
  docs/images/customer/customerFind_after.png
  docs/images/user/userUpdate_after.png
Labels: priority.Medium, type.Task, type.Docs

#311 Update UG for DeliveryViewCommand and DeliveryCreateNoteCommand
  docs/UserGuide.md
  docs/images/delivery/delivery_note.png
  docs/images/delivery/delivery_note_before.png
  docs/images/delivery/delivery_view.png
  docs/images/delivery/delivery_view_before.png
Labels: priority.Medium, type.Task, type.Docs

#339 Fix UI list cell squeeze
  src/main/java/seedu/address/model/ModelManager.java
  src/main/resources/view/LightTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
Labels: type.Bug, priority.High

#352 Add missing space to Delivery
  src/main/java/seedu/address/logic/Messages.java
Labels: type.Bug, priority.Medium

#341 Fix incorrect reference to index
  src/main/java/seedu/address/logic/commands/customer/CustomerDeleteCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryDeleteCommand.java
  src/test/java/seedu/address/logic/commands/customer/CustomerDeleteCommandTest.java
Labels: type.Bug, priority.High, severity.High

#336 Modify Predicate to create defensive copy
  src/main/java/seedu/address/model/delivery/DeliveryNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/model/delivery/DeliveryNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: priority.Low, type.Enhancement

#345 Add check for empty qn and answer
  src/main/java/seedu/address/logic/commands/user/UserRegisterCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/user/UserRegisterCommandParser.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: type.Bug, priority.High, severity.High

#348 Remove ALL from being a valid Status
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/delivery/DeliveryStatusCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/delivery/DeliveryListParserTest.java
  src/test/java/seedu/address/logic/parser/delivery/DeliveryStatusCommandParserTest.java
Labels: type.Bug, severity.Medium

#351 Fix Customer ID increment issue
  src/main/java/seedu/address/logic/commands/customer/CustomerAddCommand.java
Labels: type.Bug, priority.High

#353 Update message format for customer and delivery find
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/customer/CustomerFindCommand.java
Labels: type.Bug, severity.Medium

#354 Update help command (affects UI)
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/HelpCommand.java
Labels: type.Bug, priority.High, severity.High

#356 Update message format for Customer and Delivery Display
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/customer/CustomerAddCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerDeleteCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerEditCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryAddCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryCreateNoteCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryDeleteCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryEditCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryStatusCommand.java
Labels: type.Bug, severity.High

#360 359 UI delivery list error message
  src/main/java/seedu/address/logic/commands/delivery/DeliveryListCommand.java
Labels: priority.High

#366 Fix Customer and Delivery
  src/main/java/seedu/address/logic/commands/customer/CustomerListCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryListCommand.java
Labels: type.Bug, priority.High

#371 Add try catch for invalid date
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: type.Bug, priority.High, severity.High

#372 Update UG Formatting
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  docs/stylesheets/main.css
Labels: severity.High, type.Docs

#368 Fix Filtered Delivery List Bug
  src/main/java/seedu/address/logic/commands/customer/CustomerAddCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerDeleteCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerEditCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryDeleteCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryEditCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryFindCommand.java
  src/test/java/seedu/address/logic/commands/customer/CustomerDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerEditCommandTest.java
Labels: priority.High, severity.High

#417 Updated UG
  docs/UserGuide.md
Labels: priority.Medium, type.Docs

#416 Ug changes from pe
  docs/UserGuide.md
Labels: priority.Medium, type.Docs

#418 Fix UG based on bugs found during PED
  docs/UserGuide.md
Labels: type.Bug, priority.Low, type.Docs

#419 Update UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/getting-started/delivery_card.png
  docs/index.md
Labels: priority.Medium, type.Docs

#442 Fix typo in delivery notes error message
  src/main/java/seedu/address/model/delivery/Note.java
Labels: type.Bug, priority.Medium

#439 Update UG Formatting
  docs/UserGuide.md
Labels: priority.Medium, type.Docs

#452 Updated UG
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
Labels: priority.Medium, type.Docs

#454 Standardise UG formatting
  docs/UserGuide.md
Labels: priority.Medium, type.Docs

#441 Fix code blocks
  docs/UserGuide.md
Labels: priority.Medium, type.Docs

#474 Update PPP
  docs/AboutUs.md
  docs/team/zhonghan721.md
Labels: priority.High, type.Docs

#470 259 dg planned enhancements
  docs/DeveloperGuide.md
Labels: priority.High

#472 Update PPP
  docs/team/juliusgambe.md
Labels: priority.High

#477 Final final ug
  docs/UserGuide.md
Labels: priority.High

#451 Update UG Formatting
  docs/UserGuide.md
Labels: priority.Medium, type.Docs

#493 Cleanup ModelManager
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/DeliveryAddCommandTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerAddCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.High, type.Enhancement, severity.High

#485 Update jianyangg's PPP
  docs/team/jianyangg.md
Labels: type.Docs

#455 Update acknowledgment, glossary, NFR
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Docs

#457 Add DG - Appendix: Effort
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Docs

#484 Improve Code Quality of codebase
  src/main/java/seedu/address/logic/commands/customer/CustomerListCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerViewCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryCreateNoteCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryFindCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryStatusCommand.java
  src/main/java/seedu/address/storage/JsonAdaptedDelivery.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonDeliveryBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableDeliveryBook.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/commands/customer/CustomerViewCommandTest.java
  src/test/java/seedu/address/logic/commands/delivery/DeliveryCreateNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/delivery/DeliveryStatusCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedDeliveryTest.java
Labels: type.Bug, priority.Medium, type.Task

#506 Improve code quality - ZH
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/customer/CustomerAddCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerFindCommand.java
  src/main/java/seedu/address/logic/commands/user/UserLoginCommand.java
  src/main/java/seedu/address/logic/commands/user/UserLogoutCommand.java
  src/main/java/seedu/address/logic/commands/user/UserUpdateCommand.java
  src/main/java/seedu/address/logic/parser/customer/CustomerAddCommandParser.java
  src/main/java/seedu/address/logic/parser/user/UserLoginCommandParser.java
  src/main/java/seedu/address/logic/parser/user/UserUpdateCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/customer/Customer.java
  src/main/java/seedu/address/model/user/User.java
  src/test/java/seedu/address/logic/commands/DeliveryAddCommandTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerAddCommandTest.java
  src/test/java/seedu/address/model/user/UserTest.java
Labels: priority.Medium, type.Task

#500 Standardise UG
  docs/UserGuide.md
Labels: priority.Medium, type.Docs

#486 Update UG for password checking
  docs/UserGuide.md
Labels: priority.Medium, type.Docs

#461 Add Manual Testing to DG
  docs/DeveloperGuide.md
Labels: priority.High, type.Docs

#482 Fix Bug - Delivery details not updated
  src/main/java/seedu/address/logic/commands/customer/CustomerEditCommand.java
  src/main/java/seedu/address/model/DeliveryBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/delivery/Delivery.java
  src/main/java/seedu/address/model/delivery/UniqueDeliveryList.java
  src/test/java/seedu/address/logic/commands/DeliveryAddCommandTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerAddCommandTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerEditCommandTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerEditDescriptorTest.java
Labels: type.Bug, priority.High

#495 Improve code quality
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerDeleteCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryEditCommand.java
  src/main/java/seedu/address/logic/commands/user/UserDeleteCommand.java
  src/main/java/seedu/address/logic/commands/user/UserLoginCommand.java
  src/main/java/seedu/address/logic/commands/user/UserRecoverAccountCommand.java
  src/main/java/seedu/address/logic/commands/user/UserRegisterCommand.java
  src/main/java/seedu/address/logic/commands/user/UserUpdateCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/customer/CustomerDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/user/UserRecoverAccountCommandParser.java
  src/main/java/seedu/address/logic/parser/user/UserRegisterCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/authentication/AuthenticationData.java
  src/main/java/seedu/address/model/user/User.java
  src/test/java/seedu/address/logic/commands/DeliveryAddCommandTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerAddCommandTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/user/UserRecoverAccountCommandTest.java
  src/test/java/seedu/address/logic/commands/user/UserUpdateCommandTest.java
  src/test/java/seedu/address/logic/parser/customer/CustomerDeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/user/UserRecoverAccountCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/user/UserTest.java
Labels: priority.Medium, type.Task

#488 DG Ui - Change mentions of PersonCard to ItemCard
  docs/diagrams/UiClassDiagram.puml
Labels: priority.Medium, type.Docs

#492 Update User, Customer, Delivery class diagrams
  docs/DeveloperGuide.md
  docs/diagrams/CustomerClassDiagram.puml
  docs/diagrams/DeliveryClassDiagram.puml
  docs/diagrams/UserClassDiagram.puml
Labels: priority.Medium, type.Docs

#510 Add Logging
  src/main/java/seedu/address/logic/commands/customer/CustomerListCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerViewCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryCreateNoteCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryFindCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryStatusCommand.java
  src/main/java/seedu/address/model/delivery/DeliveryNameContainsKeywordsPredicate.java
  src/test/java/seedu/address/model/delivery/DeliveryNameContainsKeywordsPredicateTest.java
Labels: priority.Medium, type.Task

#529 Fix LoD and Add logging
  src/main/java/seedu/address/logic/parser/customer/CustomerAddCommandParser.java
  src/main/java/seedu/address/logic/parser/customer/CustomerFindCommandParser.java
  src/main/java/seedu/address/logic/parser/user/UserLoginCommandParser.java
  src/main/java/seedu/address/logic/parser/user/UserUpdateCommandParser.java
Labels: priority.Medium, type.Task

#525 Add More Testing for missing pathways
  src/test/java/seedu/address/logic/commands/delivery/DeliveryFindCommandTest.java
  src/test/java/seedu/address/logic/parser/delivery/DeliveryStatusCommandParserTest.java
  src/test/java/seedu/address/model/customer/UniqueCustomerListTest.java
  src/test/java/seedu/address/model/delivery/NoteTest.java
  src/test/java/seedu/address/model/delivery/UniqueDeliveryListTest.java
  src/test/java/seedu/address/storage/JsonDeliveryBookStorageTest.java
Labels: priority.Medium, type.Task

#531 Add logging and assertions
  src/main/java/seedu/address/logic/parser/customer/CustomerViewCommandParser.java
  src/main/java/seedu/address/logic/parser/delivery/DeliveryCreateNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/delivery/DeliveryFindCommandParser.java
  src/main/java/seedu/address/logic/parser/delivery/DeliveryStatusCommandParser.java
Labels: priority.Medium, type.Task

#504 Update Use Cases for DG
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Docs

#541 Update UG for print
  docs/UserGuide.md
  docs/images/user/userRecoverAccount_after_secretQn.png
Labels: priority.Medium, type.Docs

#539 Update DG - Command Name, Size of diagrams
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
Labels: priority.Medium, type.Docs

#519 Update DG - Update Use Cases
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Docs

#518 Update DG - Implementations
  docs/DeveloperGuide.md
  docs/diagrams/CustomerAddSequenceDiagram.puml
  docs/diagrams/UserLoginActivityDiagram.puml
  docs/diagrams/UserLoginSequenceDiagram.puml
  docs/diagrams/UserLogoutActivityDiagram.puml
  docs/diagrams/UserLogoutSequenceDiagram.puml
Labels: priority.Medium, type.Docs

#498 Update DG - Use Case and User Stories
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Docs

#505 Update DG (JY)
  docs/DeveloperGuide.md
  docs/diagrams/UserRegisterActivityDiagram.puml
  docs/diagrams/UserRegisterSequenceDiagram.puml
Labels: priority.Medium, type.Docs

#544 Add back missing update delivery
  src/main/java/seedu/address/logic/commands/customer/CustomerEditCommand.java
  src/test/java/seedu/address/logic/commands/customer/CustomerEditCommandTest.java
Labels: priority.Medium

#540 Add Test Coverage for non-trivial paths
  src/main/java/seedu/address/model/delivery/Note.java
  src/main/java/seedu/address/storage/JsonAdaptedCustomer.java
  src/main/java/seedu/address/storage/JsonAdaptedDelivery.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/customer/CustomerDeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CustomerEditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/customer/CustomerDeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/customer/CustomerViewCommandParserTest.java
  src/test/java/seedu/address/logic/parser/delivery/DeliveryCreateNoteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/delivery/DeliveryDeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/delivery/DeliveryEditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/delivery/DeliveryFindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/delivery/DeliveryStatusCommandParserTest.java
  src/test/java/seedu/address/logic/parser/delivery/DeliveryViewCommandParserTest.java
  src/test/java/seedu/address/model/delivery/DeliveryNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/delivery/DeliveryNameTest.java
  src/test/java/seedu/address/model/delivery/NoteTest.java
  src/test/java/seedu/address/model/user/PasswordTest.java
  src/test/java/seedu/address/model/user/UsernameTest.java
  src/test/java/seedu/address/storage/JsonAdaptedCustomerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedDeliveryTest.java
Labels: priority.Medium, type.Task

#538 534 code quality final
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerAddCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerDeleteCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerEditCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerFindCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerListCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerViewCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryAddCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryCreateNoteCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryEditCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryFindCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryListCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryStatusCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryViewCommand.java
  src/main/java/seedu/address/logic/commands/user/UserRecoverAccountCommand.java
  src/main/java/seedu/address/logic/commands/user/UserRegisterCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/customer/CustomerAddCommandParser.java
  src/main/java/seedu/address/logic/parser/customer/CustomerEditCommandParser.java
  src/main/java/seedu/address/logic/parser/customer/CustomerFindCommandParser.java
  src/main/java/seedu/address/logic/parser/customer/CustomerViewCommandParser.java
  src/main/java/seedu/address/logic/parser/delivery/DeliveryAddCommandParser.java
  src/main/java/seedu/address/logic/parser/delivery/DeliveryCreateNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/delivery/DeliveryDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/delivery/DeliveryEditCommandParser.java
  src/main/java/seedu/address/logic/parser/delivery/DeliveryFindCommandParser.java
  src/main/java/seedu/address/logic/parser/delivery/DeliveryListCommandParser.java
  src/main/java/seedu/address/logic/parser/delivery/DeliveryStatusCommandParser.java
  src/main/java/seedu/address/logic/parser/delivery/DeliveryViewCommandParser.java
  src/main/java/seedu/address/logic/parser/user/UserLoginCommandParser.java
  src/main/java/seedu/address/logic/parser/user/UserRecoverAccountCommandParser.java
  src/main/java/seedu/address/logic/parser/user/UserRegisterCommandParser.java
  src/main/java/seedu/address/logic/parser/user/UserUpdateCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/delivery/Delivery.java
  src/test/java/seedu/address/logic/commands/DeliveryAddCommandTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerAddCommandTest.java
  src/test/java/seedu/address/logic/parser/delivery/DeliveryAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/delivery/DeliveryDeleteCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.High, type.Enhancement

#548 Final PPP Benjamin
  docs/team/b-enguin.md
Labels: priority.High, type.Docs

#553 Update PPP - ZH
  docs/team/zhonghan721.md
Labels: type.Docs

#556 DG - Remove Undo feature
  docs/DeveloperGuide.md
Labels: priority.High, type.Docs

#557 DG - Fix broken links
  docs/DeveloperGuide.md
Labels: priority.High, type.Docs

#554 Update PPP
  docs/team/jianyangg.md
Labels: priority.High, type.Docs
