Repository AY2324S1-CS2103T-T13-3/tp, pull requests merged in 2023-09, with the labels that each got.

#45 Replace user guide
  .github/workflows/gradle.yml
  docs/UserGuide.md
Labels: priority.Med

#46 Close #40
  docs/team/b-enguin.md
Labels: documentation, priority.Low

#44 Close #31
  docs/AboutUs.md
  docs/images/b-enguin.png
Labels: documentation, priority.Low

#63 Close #36
  docs/AboutUs.md
  docs/images/zhonghan721.png
Labels: documentation, priority.Low

#62 Close #42
  docs/team/zhonghan721.md
Labels: documentation, priority.Low

#61 Close #58
  docs/UserGuide.md
Labels: documentation, priority.Low

#67 Update UserGuide for Customer and Delivery
  docs/UserGuide.md
Labels: documentation, priority.Med

#57 Close #55
  docs/team/jianyangg.md
Labels: documentation, priority.Low

#68 Update DG User Story, About Us Gambe page, User Guide User section, Raeadme image
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/juliusgambe.png
  docs/team/juliusgambe.md
Labels: priority.Med

#69 Close #58 and fix formatting issues
  docs/UserGuide.md
Labels: documentation, priority.Low

#72 Update Developer Guide - Gabriel
  docs/DeveloperGuide.md
Labels: documentation, priority.Low

#74 Update About Us and PPP - Gabriel
  docs/AboutUs.md
  docs/images/gabriel4357.png
  docs/team/gabriel4357.md
  docs/team/johndoe.md
Labels: documentation, priority.Low
