Repository AY2324S1-CS2103T-T13-3/tp, pull requests merged in 2023-10, with the labels that each got.

#75 Update DeveloperGuide NFR
  docs/DeveloperGuide.md
Labels: documentation, priority.Low

#71 Update User Guide, Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/zhonghan721.md
Labels: documentation, priority.Med

#73 UserGuide Update - Gabriel
  docs/UserGuide.md
Labels: documentation, priority.Low

#78 Standardise my portion of UG with rest of the team
  docs/UserGuide.md
Labels: documentation, priority.Med

#79 Standardise UG - Customer and Deliveries
  docs/UserGuide.md
Labels: documentation, priority.Med

#86 Update DG NFR terminology used
  docs/DeveloperGuide.md
Labels: documentation, priority.Med

#89 Remove user story documentation guide placeholder
  docs/DeveloperGuide.md
Labels: documentation, priority.Med

#84 Close #81 Update formatting for UserGuide
  docs/UserGuide.md
Labels: documentation, priority.Low

#92 Close #37 - Update README to include description
  README.md
Labels: documentation, priority.Low

#87 Close #53 - Update DG Glossary section
  docs/DeveloperGuide.md
Labels: documentation, priority.Low

#94 Update DG UC - Customer and Delivery
  docs/DeveloperGuide.md
Labels: documentation, priority.Med

#101 Update DG UC - Deliveries
  docs/DeveloperGuide.md
Labels: documentation, priority.Med

#102 Update index.md with CI Badges
  docs/index.md
Labels: documentation, priority.Low

#105 Rename Person
  LICENSE
  docs/DeveloperGuide.md
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/Customer.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCustomerDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/CustomerTest.java
  src/test/java/seedu/address/model/person/UniqueCustomerListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedCustomerTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#107 Update CLI Syntax
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: priority.Medium

#108 Add Customer List Command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerListCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Customer.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Story, priority.Medium

#110 Add Customer Add Command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/customer/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/person/Customer.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/CustomerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedCustomerTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.Medium

#111 As a register owner, I can update customer details
  src/main/java/seedu/address/logic/commands/customer/CustomerEditCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCustomerDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.Medium

#114 112 create delivery model
  src/main/java/seedu/address/model/delivery/Date.java
  src/main/java/seedu/address/model/delivery/Delivery.java
  src/main/java/seedu/address/model/delivery/DeliveryDate.java
  src/main/java/seedu/address/model/delivery/DeliveryName.java
  src/main/java/seedu/address/model/delivery/DeliveryStatus.java
  src/main/java/seedu/address/model/delivery/Note.java
  src/main/java/seedu/address/model/delivery/OrderDate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/delivery/DateTest.java
  src/test/java/seedu/address/model/delivery/DeliveryDateTest.java
  src/test/java/seedu/address/model/delivery/DeliveryNameTest.java
  src/test/java/seedu/address/model/delivery/DeliveryTest.java
  src/test/java/seedu/address/model/delivery/NoteTest.java
  src/test/java/seedu/address/model/delivery/OrderDateTest.java
  src/test/java/seedu/address/testutil/DeliveryBuilder.java
  src/test/java/seedu/address/testutil/TypicalDeliveries.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#115 113 create user model
  src/main/java/seedu/address/model/user/Password.java
  src/main/java/seedu/address/model/user/User.java
  src/main/java/seedu/address/model/user/Username.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/user/PasswordTest.java
  src/test/java/seedu/address/model/user/UserTest.java
  src/test/java/seedu/address/model/user/UsernameTest.java
  src/test/java/seedu/address/testutil/TypicalUsers.java
  src/test/java/seedu/address/testutil/UserBuilder.java
Labels: priority.High

#120 Adds user login and logout commands
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/customer/AddCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerDeleteCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerEditCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerListCommand.java
  src/main/java/seedu/address/logic/commands/user/UserLoginCommand.java
  src/main/java/seedu/address/logic/commands/user/UserLogoutCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/user/UserLoginCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CustomerDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerListCommandTest.java
  src/test/java/seedu/address/logic/parser/user/UserLoginCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.Medium

#121 Add Delivery Status Update Command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryStatusCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/delivery/DeliveryStatusCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/delivery/DeliveryStatusCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/delivery/DeliveryStatusCommandParserTest.java
Labels: type.Story, priority.Medium

#127 Add more info to help message
  docs/images/helpMessage.png
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/parser/user/UserRegisterCommandParserTest.java
Labels: priority.Medium

#123 Add Command to create a note for a delivery
  src/main/java/seedu/address/logic/commands/delivery/DeliveryCreateNoteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/delivery/DeliveryCreateNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/delivery/DeliveryStatusCommandParser.java
  src/main/java/seedu/address/model/delivery/Delivery.java
  src/main/java/seedu/address/storage/JsonAdaptedDelivery.java
  src/test/data/JsonSerializableDeliveryBookTest/typicalDeliveriesDeliveryBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/delivery/DeliveryCreateNoteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/delivery/DeliveryCreateNoteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/delivery/DeliveryStatusCommandParserTest.java
  src/test/java/seedu/address/testutil/DeliveryBuilder.java
  src/test/java/seedu/address/testutil/TypicalDeliveries.java
Labels: type.Story, priority.Medium

#134 Add Note to be displayed by delivery
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/model/delivery/Delivery.java
Labels: type.Story, priority.Medium

#143 Fix UI list refreshing bug
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/customer/AddCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerDeleteCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerEditCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryAddCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryCreateNoteCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryDeleteCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryStatusCommand.java
  src/main/java/seedu/address/logic/commands/user/UserLoginCommand.java
  src/main/java/seedu/address/logic/commands/user/UserLogoutCommand.java
  src/main/java/seedu/address/logic/commands/user/UserRegisterCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CustomerEditCommandTest.java
  src/test/java/seedu/address/logic/commands/DeliveryAddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeliveryDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/delivery/DeliveryCreateNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/delivery/DeliveryStatusCommandTest.java
  src/test/java/seedu/address/logic/commands/user/UserLoginCommandTest.java
  src/test/java/seedu/address/logic/commands/user/UserLogoutCommandTest.java
  src/test/java/seedu/address/logic/commands/user/UserRegisterCommandTest.java
Labels: type.Bug, priority.High

#174 Update DeliveryStatusCommand Command Syntax
  src/main/java/seedu/address/logic/commands/delivery/DeliveryStatusCommand.java
  src/main/java/seedu/address/logic/parser/delivery/DeliveryStatusCommandParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/delivery/DeliveryStatusCommandParserTest.java
Labels: priority.Low, type.Task

#147 Update UG for DeliveryStatusCommand
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#177 156 157 update dg user login logout
  docs/DeveloperGuide.md
  docs/diagrams/UserLoginActivityDiagram.puml
  docs/diagrams/UserLoginSequenceDiagram.puml
  docs/diagrams/UserLogoutActivityDiagram.puml
  docs/diagrams/UserLogoutSequenceDiagram.puml
Labels: priority.Medium

#148 Update UG for DeliveryCreateNoteCommand
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#182 Change customer phone number validation to 8 digits
  src/main/java/seedu/address/logic/commands/customer/CustomerAddCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CustomerAddCommandParser.java
  src/main/java/seedu/address/model/person/Phone.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/customer/CustomerAddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerAddCommandTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerEditCommandTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerEditDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/customer/CustomerAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/customer/CustomerDeleteCommandParserTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium

#185 Enable assertions in build.gradle file
  build.gradle
Labels: priority.Medium, type.Task

#190 189 update ug register account
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#194 Update register command
  src/main/java/seedu/address/logic/commands/user/UserRegisterCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/user/UserRegisterCommandParser.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/authentication/AuthenticationData.java
  src/main/java/seedu/address/model/user/User.java
  src/test/data/Authentication/authentication.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/user/UserRegisterCommandParserTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/authentication/AuthenticationDataTest.java
  src/test/java/seedu/address/testutil/TypicalUsers.java
  src/test/java/seedu/address/testutil/UserBuilder.java
Labels: priority.Low, type.Task

#192 170 update dg register account
  docs/DeveloperGuide.md
  docs/diagrams/UserRegisterActivityDiagram.puml
  docs/diagrams/UserRegisterSequenceDiagram.puml
Labels: priority.Low, type.Task

#197 Add CustomerViewCommand
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/customer/CustomerViewCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryFindCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/customer/CustomerViewCommandParser.java
  src/main/java/seedu/address/logic/parser/delivery/DeliveryFindCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/DeliveryAddCommandTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerAddCommandTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerViewCommandTest.java
  src/test/java/seedu/address/logic/commands/delivery/DeliveryFindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/customer/CustomerViewCommandParserTest.java
  src/test/java/seedu/address/logic/parser/delivery/DeliveryFindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Story, priority.Medium

#187 Update UG User Update
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Medium

#214 Correct example for register command
  src/main/java/seedu/address/logic/commands/user/UserRegisterCommand.java
Labels: type.Bug, priority.Low

#183 Add DeliveryStatusCommand implementation to DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/diagrams/DeliveryStatusCommandActivityDiagram.puml
  docs/diagrams/DeliveryStatusCommandSequenceDiagram.puml
Labels: priority.Low, type.Task

#186 Add DeliveryCreateNoteCommand implementation to DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/diagrams/DeliveryCreateNoteActivityDiagram.puml
  docs/diagrams/DeliveryCreateNoteSequenceDiagram.puml
  src/main/java/seedu/address/logic/commands/delivery/DeliveryCreateNoteCommand.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryStatusCommand.java
Labels: priority.Low, type.Task

#229 Update clear command to refresh list
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
Labels: type.Bug, priority.Medium

#191 Update DG with implementation of customer add
  docs/DeveloperGuide.md
  docs/diagrams/CustomerAddActivityDiagram.puml
  docs/diagrams/CustomerAddSequenceDiagram.puml
  docs/diagrams/UserLoginSequenceDiagram.puml
Labels: priority.Medium

#193 181 update dg list sequence diagram
  docs/DeveloperGuide.md
  docs/diagrams/implementation/delivery/DeliveryListActivityDiagram.puml
  docs/diagrams/implementation/delivery/DeliveryListSequenceDiagram.puml
  docs/diagrams/implementation/delivery/DeliveryViewActivityDiagram.puml
  docs/diagrams/implementation/delivery/DeliveryViewSequenceDiagram.puml
  src/main/java/seedu/address/logic/commands/delivery/DeliveryListCommand.java
  src/main/java/seedu/address/logic/parser/DeliveryListParser.java
  src/test/java/seedu/address/logic/parser/delivery/DeliveryListParserTest.java
Labels: priority.High

#195 Update Storage Component Implementation to DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/diagrams/ComponentManagers.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/style.puml
Labels: priority.High, type.Task

#228 Update DeveloperGuide.md to reflect current scope of update delivery status
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High, type.Task

#221 Remove Customer Sorting from UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High, type.Task

#206 Update UserGuide.md and CustomerListCommand.java
  docs/UserGuide.md
  docs/images/customer/customer_list.png
  src/main/java/seedu/address/logic/commands/customer/CustomerListCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerListCommandTest.java
Labels: type.Bug, severity.Medium

#212 Add screenshot for DeliveryStatusCommand to UserGuide.md
  docs/UserGuide.md
  docs/images/delivery/delivery_status.png
Labels: priority.Low, type.Task

#213 Add screenshot for DeliveryCreateNoteCommand to UserGuide.md
  docs/UserGuide.md
  docs/images/delivery/delivery_note.png
Labels: priority.Low, type.Task

#225 Add clarity to register command
  docs/UserGuide.md
Labels: priority.Low

#201 Add user update command
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/user/UserLoginCommand.java
  src/main/java/seedu/address/logic/commands/user/UserRegisterCommand.java
  src/main/java/seedu/address/logic/commands/user/UserUpdateCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/user/UserUpdateCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/user/User.java
  src/test/data/Authentication/authentication.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeliveryAddCommandTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerAddCommandTest.java
  src/test/java/seedu/address/logic/commands/user/UserUpdateCommandTest.java
  src/test/java/seedu/address/logic/commands/user/UserUpdateDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/user/UserUpdateCommandParserTest.java
  src/test/java/seedu/address/testutil/UpdateUserDescriptorBuilder.java
Labels: priority.Medium

#198 14 as a forgetful owner i can retrieve my account
  .gitignore
  src/main/java/seedu/address/logic/commands/user/UserRecoverAccountCommand.java
  src/main/java/seedu/address/logic/commands/user/UserRegisterCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/user/UserRecoverAccountCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/java/seedu/address/logic/commands/DeliveryAddCommandTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerAddCommandTest.java
  src/test/java/seedu/address/logic/commands/user/UserRecoverAccountCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/user/UserRecoverAccountCommandParserTest.java
  temp/authentication.json
Labels: priority.Medium, type.Task

#208 Dg diagrams gabriel
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/Gabriels Diagrams/CustomerEditActivityDiagram.puml
  docs/diagrams/Gabriels Diagrams/CustomerEditDiagram.puml
  docs/diagrams/Gabriels Diagrams/DeliveryAddActivityDiagram.puml
  docs/diagrams/Gabriels Diagrams/DeliveryAddDiagram.puml
  docs/diagrams/Gabriels Diagrams/style.puml
  docs/tutorials/TracingCode.md
  src/main/java/seedu/address/logic/commands/customer/CustomerEditCommand.java
  src/main/java/seedu/address/logic/parser/CustomerEditCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/customer/CustomerEditCommandTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerEditDescriptorTest.java
  src/test/java/seedu/address/logic/commands/user/UserUpdateCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/CustomerEditDescriptorBuilder.java
  src/test/java/seedu/address/testutil/DeliveryAddDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High

#238 Fix no delivery
  src/main/java/seedu/address/logic/parser/DeliveryListParser.java
  src/test/data/Authentication/authentication.json
  src/test/java/seedu/address/logic/parser/delivery/DeliveryListParserTest.java
Labels: type.Bug, severity.High

#200 Modify delivery list use case
  docs/DeveloperGuide.md
Labels: priority.High

#243 Remove Tag from Customer, show address for delivery view
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/customer/CustomerEditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/customer/CustomerAddCommandParser.java
  src/main/java/seedu/address/logic/parser/customer/CustomerEditCommandParser.java
  src/main/java/seedu/address/model/delivery/Delivery.java
  src/main/java/seedu/address/model/person/Customer.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/customer/CustomerEditCommandTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerEditDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/customer/CustomerAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/user/UserUpdateCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/CustomerTest.java
  src/test/java/seedu/address/model/person/UniqueCustomerListTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedCustomerTest.java
  src/test/java/seedu/address/testutil/CustomerEditDescriptorBuilder.java
  src/test/java/seedu/address/testutil/DeliveryBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium

#266 Fix Failed authentication.json creation due to missing folder
  src/main/java/seedu/address/MainApp.java
Labels: type.Bug, severity.High

#264 Create tempDir for test json file
  src/test/java/seedu/address/model/UserPrefsTest.java
Labels: type.Bug, priority.Medium

#276 Fix right click bug
  src/main/resources/view/DarkTheme.css
Labels: type.Bug, severity.High

#274 Update login command to check for stored user
  src/main/java/seedu/address/logic/commands/user/UserLoginCommand.java
  src/test/data/Authentication/authentication.json
  src/test/java/seedu/address/logic/commands/user/UserLoginCommandTest.java
Labels: priority.Medium

#265 Make window non-resizeable
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium, type.Task

#271 Edit status bar to add login info
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/view/StatusBarFooter.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeliveryAddCommandTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerAddCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.Medium, type.Task

#290 Change css file name
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: priority.Low, type.Task

#295 Update UG with feature format
  docs/UserGuide.md
  docs/images/customer/customerDelete_after.png
  docs/images/customer/customerList.png
  docs/images/user/userDelete_after.png
  docs/images/user/userDelete_before.png
  docs/images/user/userLogin_before.png
  docs/images/user/userLogout_after.png
  docs/images/user/userRecoverAccount_after.png
  docs/images/user/userRecoverAccount_after_secretQn.png
  docs/images/user/userRegister_after.png
  docs/images/user/user_freshStart.png
  src/main/java/seedu/address/logic/commands/customer/CustomerDeleteCommand.java
Labels: priority.High, type.Task

#301 Fix potential LoD breach
  src/main/java/seedu/address/logic/commands/customer/CustomerDeleteCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/DeliveryAddCommandTest.java
  src/test/java/seedu/address/logic/commands/customer/CustomerAddCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.Medium, type.Task

#252 Update DeliveryDate to stand for the Expected Delivery Date
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/Gabriels Diagrams/DeliveryAddActivityDiagram.puml
  docs/diagrams/implementation/delivery/DeliveryListActivityDiagram.puml
  docs/diagrams/implementation/delivery/DeliveryListSequenceDiagram.puml
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/Sort.java
  src/main/java/seedu/address/logic/commands/delivery/DeliveryListCommand.java
  src/main/java/seedu/address/model/delivery/DeliveryDate.java
  src/main/java/seedu/address/model/delivery/OrderDate.java
  src/test/java/seedu/address/logic/commands/DeliveryAddDescriptorTest.java
  src/test/java/seedu/address/logic/commands/delivery/DeliveryListCommandTest.java
  src/test/java/seedu/address/logic/parser/delivery/DeliveryAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/delivery/DeliveryListParserTest.java
  src/test/java/seedu/address/model/delivery/DeliveryTest.java
Labels: priority.Medium, type.Enhancement
